on: [push, pull_request]

jobs:

  build:
    name: CI
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: shellcheck
      run: shellcheck *.sh

    - name: docker build
      run: docker build $GITHUB_WORKSPACE
